### ISSUE TITLE
Unable to export page to PDF on Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by joonatanaatos** [lehtoroni/lmath-issues#49]
I am unable to export LMath pages or workbooks to PDF on version r1.9_26. Exporting to HTML works as expected.

Steps to reproduce:

1. Open LMath
2. Add some text and equations
3. Select "Tiedosto" > "Vie sivu..." > "Vie PDF-muodossa"

After these steps a loading icon will appear on the screen and all buttons become unresponsive. The program will stay in this state indefinitely.
![Screenshot from 2023-05-04 17-16-49](https://user-images.githubusercontent.com/97550588/236238409-9ee07959-ef5c-4ed5-9b5a-722ec74ef0d4.png)

Program logs:
[lmath-2023-04-04-187e71dfc75_8VlaOOuKThG6bR6V.log](https://github.com/lehtoroni/lmath-issues/files/11398560/lmath-2023-04-04-187e71dfc75_8VlaOOuKThG6bR6V.log)

Standard output:
```
- L'Math preloader r1.9 -
Data folder: /home/joonatan/.local/share/LMath
Patched: r1.9_26 from /home/joonatan/.local/share/LMath/patch/r1.9_26
[Hotfix_13] Checking if LMK
[Hotfix_13] Is patched
[Hotfix_13] Checking /tmp/.mount_LMath_riMV3P/resources/app/backend.js
[Hotfix_13] Checking backend file...
[Hotfix_13] Not an LMK build!
[2023-05-04T17:15:15.429] [INFO] default - 

-------------------------------------------------------
 (c) Roni Lehto 2023 - All rights reserved.
 L'Math ver r1.9, beta = false, dev = false, patch r1.9_26
-------------------------------------------------------

[2023-05-04T17:15:15.430] [INFO] default - Process args: ["/tmp/.mount_LMath_riMV3P/lmath","--no-sandbox"]
[2023-05-04T17:15:15.430] [INFO] default - Log dir: /home/joonatan/.local/share/LMath/logs
[2023-05-04T17:15:15.441] [INFO] default - Session ID: 187e71dfc75_8VlaOOuKThG6bR6V
[2023-05-04T17:15:15.838] [INFO] default - Statistics sent. Thanks for participating! <3
[2023-05-04T17:15:16.055] [INFO] default - Clearing temporary files.
(node:92773) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(Use `lmath --trace-warnings ...` to show where the warning was created)
(node:92773) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:92773) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:92773) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2023-05-04T17:15:16.879] [INFO] default - [ParserWorker] The parser worker is up and running!
[2023-05-04T17:15:16.908] [INFO] default - [MathjaxWorker-1] The MathJax worker is up and running!
[2023-05-04T17:15:16.955] [INFO] default - [MathjaxWorker-0] The MathJax worker is up and running!
[2023-05-04T17:15:17.993] [INFO] default - Up to date! r1.9
[2023-05-04T17:15:18.060] [INFO] default - IPC: "%cStop!"
[2023-05-04T17:15:18.061] [INFO] default - IPC: "color: red; font-family: sans-serif; font-weight: bold; font-size: 5rem; text-shadow: 0px 0px 5px Red;"
[2023-05-04T17:15:18.062] [INFO] default - IPC: "%cNever copy-paste any foreign code here. This console is not sandboxed – you can run possibly malicious code here. Please be cautious."
[2023-05-04T17:15:18.062] [INFO] default - IPC: "color: red; font-family: sans-serif; font-size: 2rem;"
[2023-05-04T17:15:18.063] [INFO] default - IPC: "%cPlease read the End User License Agreement before modifying or decompressing this software. If you have received instructions from the developer, please follow them."
[2023-05-04T17:15:18.063] [INFO] default - IPC: "color: red; font-family: sans-serif; font-size: 2rem;"
[2023-05-04T17:15:18.388] [INFO] default - IPC: "* Loading front-end plugin modules..."
[2023-05-04T17:15:18.402] [INFO] default - IPC: "Using the dark theme"
[92811:0504/171519.614807:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[92811:0504/171519.616225:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[92811:0504/171520.753737:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
Wakeup check successful
[2023-05-04T17:17:00.955] [INFO] default - Quitting. Bye bye.
Logger has finished.
Killing Mathjax workers... (total: 2)
  -> Mathjax workers left to kill: 1
  -> Mathjax workers left to kill: 0
```

**Comment by lehtoroni** [comment]
@joonatan-aatos Does this still occur if you run the AppImage from your terminal with the environment variable `OPENSSL_CONF` set to `/dev/null`?

e.g.
```
OPENSSL_CONF=/dev/null ./LMath.AppImage
```

**Comment by joonatan-aatos** [comment]
@lehtoroni Yes, it still occurs with the environment variable set.

**Comment by IiroP** [comment]
I have the same issue. If I open the DevTools console, there is an error message:
```
front.js:1 Uncaught TypeError: Cannot read properties of null (reading 'replace')
    at front.js:1:64798
    at _0x1cda88 (init.js:1:36686)
    at Object.prepareForExport (init.js:1:36792)
    at front.js:1:64264
(anonymous) @ front.js:1
_0x1cda88 @ init.js:1
prepareForExport @ init.js:1
(anonymous) @ front.js:1
setTimeout (async)
(anonymous) @ front.js:1
emit @ node:events:527
onMessage @ node:electron/js2c/renderer_init:69
```

**Comment by lehtoroni** [comment]
Thanks for the report @IiroP - this error occurs when setting the exported font family for the content, and is caused when `userSettings['pdfFont']` is null (as some older versions include quotes in the font names, the program removes them).

Could you check your `user.json` and `settings.json` files (in the data folder `~/.local/share/LMath`) and see if either of them contains the JSON key `pdfFont` and which value is assigned to it. Perhaps something has caused the `pdfFont` value to get changed to null, causing this issue.

> Since the export shows "Exporting images 2/1" (or 1/0), there might be some kind of indexing/empty list issue?
This is just a silly old bug in the progress calculation, woops... 😅

**Comment by joonatan-aatos** [comment]
@lehtoroni Yes, this fixes the issue for me too. Thanks!

**Comment by lehtoroni** [comment]
Should be fixed in full release r1.10.0. The new release now uses Electron's built-in pdf export method instead of Phantomjs, and saves all data into a temporary HTML file.
